### ISSUE TITLE
Separate user ID from token ID to allow multiple cards

### ISSUE THREAD

**Issue by charafantah** [PostTenebrasLab/DrinkingBuddyServer#8]
To allow the same user to have multiple RFID tokens (e.g. card and keychain) we need to add a UID instead of the card ID.

This would also allow us to add biometric identification in the future.

**Comment by charafantah** [comment]
For the keys
```
Create a new Table "KEYS"
key_id (PK)
user_id (FK-->Users.user_id)
key
key_type (rfid_token, rfid_card, biometric)
```
For the terminals
```
Create a new Table "TERMINAL"
terminal_id (PK)
Name
Description
```
Change the "transactions" table to add "terminal_id","key_id"
Change the "category" table to add "terminal_id" (this will be used to limit certain categories on certain terminals)

**Comment by Micmac2** [comment]
There is a table cards that allows user to have as many RFID device as needed, with reference to the ID of the user.
https://github.com/PostTenebrasLab/DrinkingBuddyServer/blob/ed7e0f5a5bd5baedf9c3c84af9aadf0b6dee062b/src/DrinkingBuddyServer/drinkingBuddyDB_declarative.py#L60
